<!DOCTYPE html>
<html class="full">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SisVigia - O seu sistema de vigias</title>
    <link href="template/css/default.css" rel="stylesheet">
    <link href="template/css/bootstrap.min.css" rel="stylesheet">
    <script src="template/js/bootstrap.min.js"></script>
    <script src="template/js/jquery.min.js"></script>
  </head>
  <body style="background: none">
    <div class="container" style="margin-top: 200px ">
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title" style="text-align: center">
                Acesso
                <a href="?controle=cadastro">
                  <span class="glyphicon glyphicon-plus" aria-hidden="true" style="float:right; font-size: 12px; line-height: 1.2"></span>
                </a>
              </h3>
            </div>
            <div class="panel-body">
              <form method="POST" action="?controle=login&acao=Autenticar">
                <div class=" input-group" title="Insira aqui o email da sua conta">
  			          <span class="input-group-addon" id="inputEmail-addon">
                    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                  </span>
	                <input name="email" id="inputEmail" class="form-control" placeholder="Digite seu email..." aria-describedby="inputEmail-addon" autofocus="" required="" type="email">
    					  </div>
                <div class=" input-group" title="Insira aqui a senha da sua conta" style="margin-top: 10px">
  			          <span class="input-group-addon" id="inputSenha-addon">
                    <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
                  </span>
	                <input name="senha" id="inputSenha" class="form-control" placeholder="Digite sua senha..." aria-describedby="inputSenha-addon" required="" type="password">
    					  </div>
                <button name="btn_login" class="btn btn-default form-control" type="submit" title="Ao preencher os campos acima, clique aqui para acessar o sistema" style="margin-top: 10px;">Entrar</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
